'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class Facesg_DireitosEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=Facesg_DireitosEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property SCD_Direitos() As DbSet(Of SCD_Direitos)
    Public Property SCD_Empresa() As DbSet(Of SCD_Empresa)
    Public Property SCD_Grupo() As DbSet(Of SCD_Grupo)
    Public Property SCD_Sistema() As DbSet(Of SCD_Sistema)
    Public Property SCD_Usuario() As DbSet(Of SCD_Usuario)

End Class
