'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SCD_Direitos
    Public Property NUM_Sistema As Integer
    Public Property NUM_Empresa As Integer
    Public Property NUM_Grupo As Long
    Public Property TXT_Menu As String
    Public Property TXT_Menu_Pai As String
    Public Property NUM_Ordernacao As Integer
    Public Property BOL_Visualizar As Boolean
    Public Property BOL_Consultar As Boolean
    Public Property BOL_Inserir As Boolean
    Public Property BOL_Alterar As Boolean
    Public Property BOL_Remover As Boolean
    Public Property NUM_Codigo As Long

    Public Overridable Property SCD_Empresa As SCD_Empresa
    Public Overridable Property SCD_Grupo As SCD_Grupo
    Public Overridable Property SCD_Sistema As SCD_Sistema

End Class
