'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SCD_Usuario
    Public Property TXT_Email As String
    Public Property TXT_Senha As String
    Public Property TXT_Nome As String
    Public Property DAT_Cancelamento As Nullable(Of Date)
    Public Property NUM_Empresa As Nullable(Of Integer)
    Public Property NUM_Grupo As Nullable(Of Long)
    Public Property User_id As Integer

    Public Overridable Property SCD_Empresa As SCD_Empresa
    Public Overridable Property SCD_Grupo As SCD_Grupo

End Class
